### ISSUE TITLE
Anfrage

### ISSUE THREAD

**Issue by robiset** [robisys/freifunk#1]
Wie geht das weiter

**Comment by robisys** [comment]
Das kann ich dir auch noch nicht sagen

**Comment by robiset** [comment]
Aber ich warte noch auf die Antwort
Anwort geändert

**Comment by robisys** [comment]
Und wie geht es nun weiter

**Comment by robiset** [comment]
Die Antwort wird nicht lange auf sich wrten lassen.

**Comment by robisys** [comment]
Hier endlich eine Antwort

**Comment by robiset** [comment]
noch weiterer Kommentar
